### ISSUE TITLE
FTP password

### ISSUE THREAD

**Issue by petrmikes** [HKFree/NAS#2]
V případě, že vytváříš ftp share tak zadáváš heslo v planttextu a ani není nahrazeno *****. Myslím že by se mělo maskovat.

**Comment by bkralik** [comment]
Nemělo, je to takhle nascvhál - FTP je dost nezabezpečenej protokol a heslo lítá v plaintextu po celym internernetu (stačí na libovolné wifi nahodit tcpdump a uvidíš ho). Proto mi přijde dobré zdůraznit potřebu "separátního hesla" pro tuhle službu tím, že se tam bude ukazovat a nebudou tam hvězdičky...

Nechám ticket otevřený, kdyby ještě někdo měl názor, ale já osobně bych to neměnil..

**Comment by n0by** [comment]
...a presne prave z tohohle duvodu bych FTP vubec nezavadel a pouzil FTPS
