### ISSUE TITLE
editace velikosti složky

### ISSUE THREAD

**Issue by cermis** [HKFree/NAS#4]
Pokud by to bylo jen trochu možné, bylo by vhodné udělat editaci velikosti složky. Při prvním založení složky např. pro zálohy fotografií se těžko odtuší, jak bude za rok objemná a po dvou letech místo ve složce dojde. Nyní bez možnosti jakkoliv upravit velikost znamená, složku vyprázdnit (např. 300GB), smazat, vytvořit novou větší a zas těch 300GB tam nahrát.

**Comment by bkralik** [comment]
Implementováno v commitu 201c278, nasazeno na nas.hkfree.org :-). Pokud můžeš otestuj to, dík!

**Comment by cermis** [comment]
Bezvadné, otestováno změnou atributu velikosti a popisku u jedné složky, změna proběhla. Moc užitečná funkce. Díky.
